### ISSUE TITLE
pause_finder error

### ISSUE THREAD

**Issue by yhj4659** [sheridar/spt5-mutants#1]
Hello.
I'm following try your code to obtain the pausing zone.
When I'm trying to execute "pause_finder" with the basic option, the error occurs because the file "find_pauses" is not in directory "src".
First time, I guessed the file "find_pauses.cpp" is the right one, but I think it is not appropriate for the "pause_finder".

"line 183: ~/spt5-mutants-v0.1.0/sheridar-spt5-mutants-80d58ef/src/find_pauses: No such file or directory"

The above is the error code.
Please help me. Is there the other code named "finde_pauses" or "pause_finder" should be fixed?

**Comment by sheridar** [comment]
Hi, the find_pauses.cpp code just has to be compiled on your system, you can try running this:

g++ -std=c++11 find_pauses.cpp -o find_pauses

**Comment by yhj4659** [comment]
Thank you!
